In [1]:
import torch

# 初识张量

> 张量可以理解为矩阵

## 创建张量

In [4]:
data = [[1, 24], [2, 41]]

x_data = torch.tensor(data)

print(x_data)

tensor([[ 1, 24],
        [ 2, 41]])


### 通过已有张量生成一个张量

In [3]:
x_ones = torch.ones_like(x_data)

print(x_ones)

tensor([[1, 1],
        [1, 1]])


### 生成一个随机值的张量

In [4]:
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(x_rand)

tensor([[0.7294, 0.2896],
        [0.1052, 0.5331]])


### 通过指定数据维度生成张量

In [5]:
shape = (2, 3)

rand_tensor = torch.rand(shape)
print(rand_tensor)
zero_tensor = torch.zeros(shape)
print(zero_tensor)
one_tensor = torch.ones(shape)
print(one_tensor)

tensor([[0.7539, 0.8798, 0.8860],
        [0.4352, 0.9908, 0.2856]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# 张量的属性

In [8]:
tensor = torch.rand(3, 4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.4416, 0.1429, 0.3369, 0.4265],
        [0.2402, 0.1920, 0.0064, 0.2647],
        [0.5592, 0.1501, 0.7382, 0.8389]])
torch.Size([3, 4])
torch.float32
cpu


# 张量的运算

全部的运算操作见 [文档](https://pytorch.org/docs/stable/torch.html)

## 索引&切片

In [21]:
tensor = torch.ones(4, 4);
tensor[0:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## 拼接

In [28]:
tensor = torch.cat([tensor, tensor, tensor], dim=1)

print(tensor)

tensor([[1., 0., 1.,  ..., 0., 1., 1.],
        [1., 0., 1.,  ..., 0., 1., 1.],
        [1., 0., 1.,  ..., 0., 1., 1.],
        ...,
        [1., 0., 1.,  ..., 0., 1., 1.],
        [1., 0., 1.,  ..., 0., 1., 1.],
        [1., 0., 1.,  ..., 0., 1., 1.]])


## 乘积 & 矩阵乘法

In [31]:
tensor = torch.ones(3, 4)

print(tensor.mul(tensor))
# equal
print(tensor * tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## 赋值

In [35]:
tensor = torch.zeros(4, 4)
tensor[:,1] = 4
tensor.add_(2)
print(tensor)

tensor([[2., 6., 2., 2.],
        [2., 6., 2., 2.],
        [2., 6., 2., 2.],
        [2., 6., 2., 2.]])
